version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: tdd-clean-node-api
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/TDD_CLEAN_NODE_API/dist
    ports:
      - "5050:5050"
    links:
      - mongo
    